### ISSUE TITLE
Any plan for maven artifact distribution ?

### ISSUE THREAD

**Issue by jvelo** [Mangopay/mangopay2-java-sdk#1]

**Comment by Tony-Hunter** [comment]
This would be really useful - do you have any plans to distribute to Maven central any time soon?

**Comment by hobailey** [comment]
Hey there, could one of you contact me on support@mangopay.com please?

**Comment by blackleg** [comment]
Have any plans to distribute to Maven central or another maven repo?

**Comment by hobailey** [comment]
If anyone has the time and also experience of Maven to help us with this, it would be hugely appreciated :-)

**Comment by youribonnaffe** [comment]
Actually, implementing #3 would make it easier, the[bintray plugin](https://github.com/bintray/gradle-bintray-plugin) could then be used to publish the JAR on JCenter
It would simplify dependency management too, no need to copy a bunch of JARs and no need to maintain the README for instance (that is outdated since SLF4J is needed as well).
I'll be happy to help but it would be better to publish it under your name (Mangopay) on Bintray

**Comment by hobailey** [comment]
That would be great @youribonnaffe, thank you. Using Gradle to build the SDK wouldn't of course present any breaking changes would it?
As for submission, I'm happy to take care of this - it would indeed be best as you say.

**Comment by ArnaudT** [comment]
Hi,

I am not sure if it is useful for you but we are using this pom.xml to deploy in our local maven repository.
https://gist.github.com/ArnaudT/9b03f72e8929894fecce16f88bad6be1

and the command:
`mvn deploy:deploy-file -DpomFile=pom.xml -Dfile=mangopay2-java-sdk-1.0.7.jar -DrepositoryId=depop.s3.releases -Durl=s3://depop-maven-repository/releases`

cheers.

**Comment by hobailey** [comment]
Hey @ArnaudT, that's really useful, thank you - the missing POM file is exactly what's currently blocking us being able to add this to jCenter etc. Do you think you could do a PR with it please?

**Comment by youribonnaffe** [comment]
Since the maven plugin is used, you can also
run generatePomFileForMavenPublication or install to generate a pom.xml
file (gradle install, then in build/poms/pom-default.xml).

**Comment by hobailey** [comment]
Hey everyone, just to say that we've now resolved these issues (and released v1.1.0). Everything is now correctly in sync with Bintray and the POM files are correctly named/included. We've requested that it be made available Maven central and are just waiting for it to be accepted :-)

**Comment by hobailey** [comment]
Hey again - just to let you know that the package has been accepted on jCentral, so it's now available there :-)
