### ISSUE TITLE
Missing feature - GET Settlement

### ISSUE THREAD

**Issue by aliniftemi** [Mangopay/mangopay2-java-sdk#103]
Hi guys,

This API is not available in maven repo:
https://api.sandbox.mangopay.com/v2.01/m3application5test/settlements/38334743

I am using this maven repo:
https://mvnrepository.com/artifact/com.mangopay/mangopay2-java-sdk/2.2.0

Basically get settlement is not yet implemented and for us it is an issue. I would like to know if there is a real chance that you guys add this functionality in the next days or we should customize our code to perform this function with regular GET calls.

Thanks a lot
A

**Comment by mickaelpois** [comment]
Hello @aliniftemi,
We are trying to get our SDK more and more complete and compliant to our API docs.
This endpoint is clearly missing, and we will try to add it shortly.
We will add a list of disputes that could be settled too, maybe this could be useful too for your disputes workflow and your business integration.

I'll keep you posted about every update with this subject (this week I hope).

Mickaël

**Comment by aliniftemi** [comment]
Hi Mickael,

In the meantime, I took your library and modified by myself. If this library is open source maybe I can try to add my branch for review (if it helps)...

Thanks

**Comment by mickaelpois** [comment]
@aliniftemi 

Feel free to propose your PR here, and if everything works fine, I'll be very pleased to merge it to our master branch and release a new version of our SDK !

**Comment by mickaelpois** [comment]
#118
