### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by mkoppanen** [Mangopay/mangopay2-java-sdk#11]
Hello,

I am just starting to use this library and I am slightly confused about error handling. Seems like most of the errors throw generic exceptions and the error messages are marshalled into something that is not machine readable (https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/com/mangopay/core/RestTool.java#L885).

As mentioned, I am just starting with the library but I don't see an easy way to handle different types of errors coming back from the library. Am I missing something?

**Comment by hobailey** [comment]
Hi @mkoppanen - our suppport team will get in touch with directly by email to help with this :-)
