### ISSUE TITLE
SSL certificate for OpenJDK 10

### ISSUE THREAD

**Issue by adebrnt** [Mangopay/mangopay2-java-sdk#119]
We're migrating our app to OpenJDK 10 and because your SSL certificate is not in the trust store, we need to add it manually.
Now, we're getting the following error:
`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.`

Could you provide us with a link to your sandbox and production certificates?

**Comment by mickaelpois** [comment]
Hello,

Our certificates infos are available on our docs [here](https://docs.mangopay.com/guide/ssl-information)

**Comment by WarayAmine** [comment]
Hello @mickaelpois ,

I'm having the exact same issue. The provided link redirect to a new page.
