### ISSUE TITLE
Active == null

### ISSUE THREAD

**Issue by mkoppanen** [Mangopay/mangopay2-java-sdk#12]
Hello,

on sandbox I am getting following card structure back (dumped as json):

{"Id":"8327520","Tag":null,"CreationDate":1441068315,"ExpirationDate":"1218","Alias":"356999XXXXXX0140","CardProvider":"MASTERCARD","CardType":"CB_VISA_MASTERCARD","Product":"   ","BankCode":"unknown","Active":null,"Currency":"GBP","Validity":"VALID","readOnlyProperties":["Id","CreationDate","ExpirationDate","Alias","CardProvider","CardType","Product","BankCode","Active","Currency"],"values":{},"dependentObjects":{},"subObjects":{}}

As you can see Active is null instead of false. Is this card valid or invalid?

**Comment by hobailey** [comment]
Hi @mkoppanen, yes this card is indeed still active. You can always check using the Dashboard though (dashboard.sandbox.mangopay.com) if you are in doubt.
And in the mean time, perhaps it's just a problem with Java decoding the response - do you have the same problem for other Cards?

**Comment by mkoppanen** [comment]
@hobailey,

yes, looks like all my cards are coming back with Active == null at the moment. This was kind of a surprise (and broke some stuff) we didn't expect this to be ever null.

**Comment by hobailey** [comment]
Hmm, fair enough - I'll look into this further and let you know. 
Could you confirm whether it's a new problem, or something that has always been happening, but you've only just realised?

**Comment by mkoppanen** [comment]
I was away for business 8th - 18th Sept and before I left it was definitely working. Our code was checking if (card.Active == false) so there is no way this would've ever worked if it was always null. My initial thought was that something happened to old cards on Sandbox but that doesn't seem to be the case?

**Comment by hobailey** [comment]
Hmm, this is strange. Have you updated your SDK version at any point since then? 
Just to confirm, I checked the logs for your GET calls on this card this morning and I can see that we definitly giving your a "Active: true" response.

**Comment by mkoppanen** [comment]
Looking at the repository history the last update was 29 days ago

**Comment by hobailey** [comment]
When you say "the repository", I presume you mean _your_ repo? Because we've updated the Java one several times since then.

**Comment by mkoppanen** [comment]
Sorry, by the repository I meant our side. I.e. I last updated the jar file 29 days ago

**Comment by hobailey** [comment]
OK, so just to be sure, it's definitly _since_ this update that the problem has started? Sorry for the questions, but I'm really struggling to understand what's happened (as nothing has changed on the API side, and seemingly nothing has changed with your copy of the SDK)

**Comment by mkoppanen** [comment]
To me the behaviour looks like the problem started out of the blue (as mentioned, I've been away and have not touched the code). I can take a look at updating to latest version tomorrow. The current jar:
$ md5 mangopaysdk.jar 
MD5 (mangopaysdk.jar) = e59e6b786c93326205e855320a68acc4

**Comment by hobailey** [comment]
OK, well let me know how you get on with the update :-)

**Comment by mkoppanen** [comment]
@hobailey,

Looks like update brought some new issues. I am looking at our logs while loading cards and here is a json representation of the card list item:

    [info] - application - {"Id":"8298885","Tag":null,"CreationDate":1440780370,"UserId":"8298687","Country":"USA","ExpirationDate":"1218","Alias":"356999XXXXXX0132","CardProvider":"MASTERCARD","CardType":"CB_VISA_MASTERCARD","Product":"   ","BankCode":"unknown","Active":null,"Currency":"GBP","Validity":"INVALID","readOnlyProperties":["Id","CreationDate","UserId","Country","ExpirationDate","Alias","CardProvider","CardType","Product","BankCode","Active","Currency"],"values":{},"dependentObjects":{},"subObjects":{}}

I will do a bit more investigation on what's actually going on here

**Comment by mkoppanen** [comment]
The "weird" part being is that we have never added anything with USA countrycode and Active is still null

**Comment by hobailey** [comment]
Hi @mkoppanen, thanks for following up. So does your PR fix the problem? It looks as though it was just  a Java handling issue, but I'm not why it hasn't affected you/anyone else before...
For the Country, this is the just a field that is deduced on our side from the Card and is not supplied by you. Previously this field was missing from the Java Card Object, hence you hadn't noticed it before :-)

**Comment by mkoppanen** [comment]
@hobailey,

the problematic part is that it looks like the Boolean handling has been missing from there always. So basically boolean fields would've never worked. In our code we had a check like:
 
    if (card.Active == false) { continue; }

To skip over inactive cards. I am not sure if this was ever well-tested on our side because it was throwing a null pointer exception due to Active being null. After applying the change in PR, rebuilding the jar I get the following JSON representation of the card:

    [info] - application - {"Id":"8659154","Tag":null,"CreationDate":1443101684,"UserId":"8298687","Country":"unknown","ExpirationDate":"1118","Alias":"411111XXXXXX1111","CardProvider":"unknown","CardType":"CB_VISA_MASTERCARD","Product":"unknown","BankCode":"unknown","Active":true,"Currency":"GBP","Validity":"UNKNOWN","readOnlyProperties":["Id","CreationDate","UserId","Country","ExpirationDate","Alias","CardProvider","CardType","Product","BankCode","Active","Currency"],"values":{},"dependentObjects":{},"subObjects":{}}

As you can see Active is now a boolean as excepted.

**Comment by hobailey** [comment]
OK, great stuff - thanks very much for your help with resolving that :-)

**Comment by mkoppanen** [comment]
@hobailey,

no problem. In the future you might want to look into moving into a bit more robust JSON parser. The code in the RestTool class looks brittle to me in some cases. There is another case of missing boolean handling here but I am not sure if you ever return array of booleans from the API:

https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/com/mangopay/core/RestTool.java#L664

**Comment by hobailey** [comment]
Hey @mkoppanen, sorry for the delay getting back to you, and thanks for this feedback - we'll take a look and try and see if it can be tidied up/made more robust :-)
