### ISSUE TITLE
Payin whit preauthorization error

### ISSUE THREAD

**Issue by jonathan-bibas** [Mangopay/mangopay2-java-sdk#129]
I cannot do a payin with a preauthorization.
The error returned is:
```
Execution is not defined or it is not object type
```
So i tryed to add to execution the type Preauthorization BUT the class PayinExecutionDetailsPreauthorization doesn't exist.

Please tell me what is the way to create a payin from a preauthorization?

**Comment by mickaelpois** [comment]
Hello @jonathan-bibas,

Is your issue still relevant ?
Feel free to be inspired by our PayIn Preauth. unit test here! https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/test/java/com/mangopay/core/PayInApiImplTest.java#L150
