### ISSUE TITLE
View a Settlement Transfer does not return a Transfer

### ISSUE THREAD

**Issue by CornelZ** [Mangopay/mangopay2-java-sdk#130]
this API endpoint
.../v2.01/:ClientId/settlements/:SettlementId returns a Transfer type object

the SDK transforms this Transfer type object into a SettlementTransfer object (the one needed to create a settlement) wich has way less information about the transfer

class SettlementApiImpl 
method get(String id) returns SettlementTransfer

either this method should return Transfer, either a new method to return Transfer is needed

What do you guys think about this ?

Thank you
Cornel

later edit:
I noticed that the return object by the api has a field RepudiationId. Field that does not exist in the Transfer object. And I didn't find a similar object in the com.mangopay.entities package.

**Comment by CornelZ** [comment]
Hi,

How can I make a pull request ? Is there a procedure to follow ?

Thanks

**Comment by SoloJr** [comment]
@CornelZ have you opened any pull requests?

**Comment by CornelZ** [comment]
hi @SoloJr 
There are different solutions to this problem. The best one in my opinion will break compatibility with previous SDK version. So this is the first reason I did not make a PR.
The second reason is because it passed more then a year and I don't know if you already fix it :)

**Comment by SoloJr** [comment]
@CornelZ you could open a PR, it would be easier for us to take care of your needs :). The only problem right now is that due to some sdk issues, these settlement transfers cannot be tested, so we can only wait..

**Comment by CornelZ** [comment]
Hi @SoloJr 

I opened a PR #191
