### ISSUE TITLE
UBO Declaration -  Do we need to create a mangopay user for each entry?

### ISSUE THREAD

**Issue by felixhagspiel** [Mangopay/mangopay2-java-sdk#144]
As I understand from [your endpoint documentation ](https://docs.mangopay.com/endpoints/v2.01/ubo-declarations#e1027_create-a-ubo) we can create a POST with `firstName`, `lastName`, etc... to specify the owners holding 25% or more. However, in the Java SDK I can only specify a mangopay user-ID. Does this mean that I have to create a new mangopay user for each `DeclaredUbo`? 
I am using Java SDK 2.5.0. If this is not the case in the latest version please [update your maven project as well](https://github.com/Mangopay/mangopay2-java-sdk/issues/139). Thanks!

**Comment by mickaelpois** [comment]
Hello @felixhagspiel,

Yes, unfortunately we encountered issues with SDK last version publish.
Automated publishing fixes will be tried today thanks to https://github.com/Mangopay/mangopay2-java-sdk/tree/feature/update_gradle_script devs.

**Comment by mickaelpois** [comment]
@felixhagspiel Quick answer to your last question.
Thanks to our new UBODeclaration submission process, you need to create:
1. a legal user
2. a ubo declaration linked to your legal user
3. one to four UBOs (they are not users anymore, but proper UBO objects now) linked to your declaration
4. submit your declaration

Feel free to tell me is something is not clear enough !

1.
