### ISSUE TITLE
UBO Declaration - Get All UBO Declarations by UserId throws exception

### ISSUE THREAD

**Issue by dsagoyan** [Mangopay/mangopay2-java-sdk#149]
Get all UBO Declarations By UserId throws an exception (ver: mangopay2-java-sdk: 2.8.0).
The method was called: com.mangopay.core.APIs.implementation.UboDeclarationApiImpl.getAll

Http Response Code: 200
Http Response Str: [{"Id":"68330964","UserId":"65550987","CreationDate":1567762541,"ProcessedDate":null,"Status":"CREATED","Reason":null,"Message":null,"Ubos":[]}]

Fails on casting to UBO Declration entity: {"Id":"68330964","UserId":"65550987","CreationDate":1567762541,"ProcessedDate":null,"Status":"CREATED","Reason":null,"Message":null,"Ubos":[]}

Log file:
[ubo_declaration_exception.txt](https://github.com/Mangopay/mangopay2-java-sdk/files/3584050/ubo_declaration_exception.txt)

**Comment by mickaelpois** [comment]
All the UBODeclaration calls issues should have been fixed by 2.8.1 release.
Unit test on getAllUBODeclaration is now green, please feel free to give me some feedback is something is wrong.

Mickaël
