### ISSUE TITLE
NPE on getPayin()

### ISSUE THREAD

**Issue by julientard** [Mangopay/mangopay2-java-sdk#156]
Hello, 

On the following operation:
https://dashboard.sandbox.mangopay.com/Refund/59621974
With a getPayInApi().get(), we have a NPE on payIn.getPaymentType. It seems to be a special payin type.

Here is the stacktrace:

java.lang.NullPointerException: null
at
com.mangopay.core.deserializer.PayInDeserializer.deserialize(PayInDeserializer.java:25)
at
com.mangopay.core.deserializer.PayInDeserializer.deserialize(PayInDeserializer.java:19)
at
com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.Gson.fromJson(Gson.java:927)
at com.google.gson.Gson.fromJson(Gson.java:994)
at com.google.gson.Gson.fromJson(Gson.java:967)
at com.mangopay.core.RestTool.castResponseToEntity(RestTool.java:518)
at com.mangopay.core.RestTool.doRequest(RestTool.java:420)
at com.mangopay.core.RestTool.request(RestTool.java:144)
at com.mangopay.core.RestTool.request(RestTool.java:168)
at com.mangopay.core.APIs.ApiBase.getObject(ApiBase.java:303)
at
com.mangopay.core.APIs.implementation.PayInApiImpl.get(PayInApiImpl.java:46)
at
com.hopwork.payment.service.DefaultMangoPayService.getPayIn(DefaultMangoPayService.java:411)

**Comment by mickaelpois** [comment]
Hello @julientard, 

Are you trying to get informations from the refund itself, or the transaction related to the refund?
On both cases, this is not a Payin but a Payout or a Refund, and you need to use `PayoutApi` or `RefundApi`.

Please feel free to share your feedback and some extra insights, I'll be very happy to help you solve your issue !

Mickaël

**Comment by julientard** [comment]
I'm trying to get more information on a transaction, whatever it is. I first call TransactionAPI, and for each transaction i make a call on PayinAPI, PayoutApi or TransferAPI depending on the field `type` of the transaction.

For this particular transaction, which is I agree a specific case (refund of a payout), the TransactionApi tells me it's a payin. So it seems logical to me to make a call on the PayinAPI.

There is several inconsistent things:
- The TransactionAPI should not say it's a PAYIN if it's not, but it's missing a REFUND type maybe
- The PayinAPI should not return a result if you consider it's not a PAYIN, it should return a 404.
- Before upgrading to SDK 2.8 (I was on SDK 1.2), it was working perfectly fine. So it's really how the sdk handle the API response.

I don't know what's the best way to handle these transactions, but I thing it needs an improvment somewhere.

**Comment by kaczuss** [comment]
In this code 
```java
 PayIn payIn = new Gson().fromJson(object.toString(), PayIn.class);
        switch (payIn.getPaymentType()) {
            case BANK_WIRE:
                PayInPaymentDetailsBankWire payInDetails = new PayInPaymentDetailsBankWire();
                if (object.has("DeclaredDebitedFunds") && !object.get("DeclaredDebitedFunds").isJsonNull())
                    payInDetails.setDeclaredDebitedFunds((Money) context.deserialize(object.get("DeclaredDebitedFunds"), Money.class));
                if (object.has("DeclaredFees") && !object.get("DeclaredFees").isJsonNull())
                    payInDetails.setDeclaredFees((Money) context.deserialize(object.get("DeclaredFees"), Money.class));
                if (object.has("BankAccount") && !object.get("BankAccount").isJsonNull())
                    payInDetails.setBankAccount((BankAccount) context.deserialize(object.get("BankAccount"), BankAccount.class));
                if (object.has("WireReference") && !object.get("WireReference").isJsonNull())
                    payInDetails.setWireReference(object.get("WireReference").getAsString());

                payIn.setPaymentDetails(payInDetails);
                break;
```

first line fails, because `Gson` will already try to deserialize `payInDetails`  or `executionDetails` and will fail because those are interfaces.
