### ISSUE TITLE
Inconsistency between CardPreAuthorization and PayInExecutionDetailsDirect

### ISSUE THREAD

**Issue by federicogatti** [Mangopay/mangopay2-java-sdk#157]
In _com.mangopay.entities.CardPreAuthorization_ there is **SecureModeNeeded** attribute
` @SerializedName("SecureModeNeeded")
    private String secureModeNeeded` with _getter_ and _setter_ method.
In _com.mangopay.entities.subentities.PayInExecutionDetailsDirect_ there is also **SecureModeNeeded** attribute, but instead of _getter_ method there is "isSecureModeNeeded()" function that return a Boolean

``` 
public boolean isSecureModeNeeded() {
        if (ObjectTool.nonNull(secureModeNeeded)) {
            return Boolean.parseBoolean(secureModeNeeded);
        } else {
            return false;
        }
}
```

in order to maintain consistency between Entities is better to introduce the *isSecureModeNeeded()* also in CardPreAuthorization Class, or remove it in from PayInExecutionDetailsDirect

**Comment by mickaelpois** [comment]
Dear @federicogatti,

Thanks for your feedback, which is good :)
We will enhance this ASAP and deprecate old getters and setters, ensuring this is not breaking.

**Comment by mangomaxoasis** [comment]
Fix released
