### ISSUE TITLE
Errors when get then update a user without some fields

### ISSUE THREAD

**Issue by julientard** [Mangopay/mangopay2-java-sdk#158]
Hello,

Here is a bug I have with the version 2.8.1.

When I `getUserApi().get()` a user without certains missing fields, like LegalRepresentativeAddress, or HeadquartersAddress, or Address, we have a error from the API when trying to update the exact same object, because the subfields of these fields are null. 

For example: 
User 54987274 in the sandbox.

Response:
{
  "responseHttpCode": 400,
  "responseHttpDescription": "Bad request",
  "apiMessage": "One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.",
  "type": "param_error",
  "id": "674d1e9c-2ce3-4cbe-95be-c76f6a70ea07#1569417378",
  "date": 1569417379,
  "errors": {
    "LegalRepresentativeAddress.AddressLine1": "The AddressLine1 field is required.",
    "LegalRepresentativeAddress.City": "The City field is required.",
    "HeadquartersAddress.AddressLine1": "The AddressLine1 field is required.",
    "LegalRepresentativeAddress.Country": "The Country field is required.",
    "HeadquartersAddress.City": "The City field is required.",
    "HeadquartersAddress.Country": "The Country field is required."
  }
}

It seems the SDK should not instanciate a object if all subfields are null, or the API should not refuse these fields which are optional.

Thanks for the fix.

**Comment by mickaelpois** [comment]
Hello @julientard 

We're looking at this inconsistency issue, and will come back to you with some fresh update.

**Comment by iulian03** [comment]
Hello

I made a fix for this, the SDK will not instantiate an Address object if all the subfields are null.

**Comment by catacraciun** [comment]
Fixed in https://github.com/Mangopay/mangopay2-java-sdk/pull/189
