### ISSUE TITLE
API returns weird message with no error code

### ISSUE THREAD

**Issue by mjkhaled** [Mangopay/mangopay2-java-sdk#159]
Hello,
My issue is that I was trying to call the API below:
https://api.sandbox.mangopay.com/v2.01/clientId/users
Knowing that I've passed the authorization & clientId correctly, but I still received the result below with every API I called.

[Message] => This endpoint is not available for your account
[Type] => forbidden_ressource
[Id] => 34e3121f-d603-4886-ac1a-857a3dca00e3#1570900712
[Date] => 1570900714
[errors] => 

Can anyone help please ?

Thanks in advance.

**Comment by mickaelpois** [comment]
@mjkhaled Good evening,
I cannot see any clientID "mjk_khaled" on our Sandbox records.
Are you sure of your account registration and credentials?

Feel free to contact our dedicated support team 👍
