### ISSUE TITLE
Allow updating of BankAccount Tag property via the Java SDK 

### ISSUE THREAD

**Issue by Tony-Hunter** [Mangopay/mangopay2-java-sdk#16]
It would be useful to be able to update the `BankAccount.Tag` property after a BankAccount is created. I can see how to do this via HTTP, but not via the Java SDK.

Use case: our users have a single 'active' bank account. They are allowed to add a new account as/when they like and after doing so, previous accounts on the system are ignored. Ideally we'd like to mark the previous accounts as "Inactive" via the `Tag` property to avoid confusion.

Please let me know if you'd like more details.

**Comment by hobailey** [comment]
Hi @Tony-Hunter, thanks for your detailed feedback. There is infact no PUT method available for bank account resources - not even for the Tag. This is something we're hoping to update in the future though :-)
