### ISSUE TITLE
URL for payline template should not get parsed by GSON in Rest-Tool

### ISSUE THREAD

**Issue by felixhagspiel** [Mangopay/mangopay2-java-sdk#168]
Hello,

we are passing a template URL to customize the design of the credit-card page.

This is the URL we pass: 
`https://anypage.de/app/?amount=350&lang=de`

This is the URL after the entity is [parsed by the RestTool in `doRequest()`](https://github.com/Mangopay/mangopay2-java-sdk/blob/f5dbb8238717a20cd693bc48a5a43aaf330baa28/src/main/java/com/mangopay/core/RestTool.java#L367):
`https://anypage.de/app/?amount\u003d350\u0026lang\u003dde`

This results in an error on payline and the default mangopay template is used. I think that if HTML-Escaping is disabled for this value it should solve the problem: https://stackoverflow.com/questions/16558709/gson-issue-with-string

This is how we set the template-URL:

	        PayInExecutionDetailsWeb exec = new PayInExecutionDetailsWeb();
		PayInTemplateURLOptions templateOptions = new PayInTemplateURLOptions();
		templateOptions.PAYLINE = "https://anypage.de/app/?amount=350&lang=de";
		exec.setTemplateURLOptions(templateOptions);
                ...

**Comment by iulian03** [comment]
Hello.

A PR was merged with the fix.

**Comment by felixhagspiel** [comment]
Hello @iulian03 , thank you! When will the new version be released to maven (i.e. v2.8.2)? So I can update my dependencies?

**Comment by mickaelpois** [comment]
@felixhagspiel Version 2.10.x contains GsonBuilder fix 👍
