### ISSUE TITLE
com.mangopay.entities.UboDeclaration processedDate is an Integer but should be long

### ISSUE THREAD

**Issue by LeaklessGfy** [Mangopay/mangopay2-java-sdk#170]
In the project, the SDK represent a Date value as long timestamp (in second) but in the new class :
`com.mangopay.entities.UboDeclaration` the "processedDate" is an int.

First, is there any reason behind this choice ?
Second, I think it provock an incoherent processedDate with real values. It would be more reasonable to keep `Long` as in `com.mangopay.entities.KycDocument`

Thanks

**Comment by mangomaxoasis** [comment]
Fixed in latest release
