### ISSUE TITLE
TemplateURL seems ignored on Test environment

### ISSUE THREAD

**Issue by oryam** [Mangopay/mangopay2-java-sdk#177]
Hi,

Is the `TemplateURL` property is available on Test environment?
I am sending a payin request to `https://api.sandbox.mangopay.com/v2.01/.../payins/card/web/` on Homologation, but the `TemplateURL` is always `https://api.sandbox.mangopay.com/...`

Example of response :
```
{
  "PaymentType" : "CARD",
  "Id" : "76500926",
  "CreationDate" : 1583327231000,
  "AuthorId" : "...",
  "CreditedWalletId" : "...",
  "CreditedUserId" : "...",
  "DebitedFunds" : {
    "Currency" : "EUR",
    "Amount" : 20.0
  },
  "Fees" : {
    "Currency" : "EUR",
    "Amount" : 0.0
  },
  "CreditedFunds" : {
    "Currency" : "EUR",
    "Amount" : 20.0
  },
  "Nature" : "REGULAR",
  "Status" : "CREATED",
  "Type" : "PAYIN",
  "ExecutionType" : "WEB",
  "ReturnURL" : "http://test.net/test?transactionId=76500926",
  "CardType" : "CB_VISA_MASTERCARD",
  "SecureMode" : "DEFAULT",
  "Culture" : "FR",
  "TemplateURL" : "https://api.sandbox.mangopay.com/Content/PaylineTemplate?rp=...&transactionId=76500926",
  "StatementDescriptor" : "cart1",
  "RedirectURL" : "https://homologation-secure-p.payline.com/webpayment/step2.do?reqCode=prepareStep2&token=..."
}
```

**Comment by Riwak** [comment]
Hello @oryam 

For the Web PayIn you have two options. 

- Option 1 : `TemplateURLOptions` parameters =  `null` 

>  The `TemplateURL` in the JSON response will refer to the link of the payment page (always the same `https://api.sandbox.mangopay.com/` links)

- Option 2 : `TemplateURLOption` parameters =  A URL to an SSL page to allow you to customise the payment page.  TemplateURLOptions ": { "PAYLINEV2": "your links" },

>  The `TemplateURL` in the JSON response will be the link to the payment page (your custom payment page )


You can find more info here : https://docs.mangopay.com/endpoints/v2.01/payins#e269_create-a-card-web-payin.

Have a nice day,

**Comment by oryam** [comment]
Thanks for your answer.
We noticed another reason that was blocking the display of the custom page. It is that we have compressed page (gzip). So after realizing this issue, we did some updates.

Now, it is working with an old template rendering when giving { "Payline": "custom link links" }
Not working, when trying with { "Paylinev2": "custom link links" } . TemplateURL and RedirectURL are retruned with the same value ( given value set in TemplateURLOptions).

**Comment by oryam** [comment]
So, I tried for `TemplateURLOption` with `{ "Payline": "custom link links" }` (Paylinev2 is not working, or I got the default v2 page, if I do not set `TemplateURLOption` )
Then I am getting a correct `TemplateURL` value such as `"TemplateURL" : "https://mysite.../payment.html?orderRef=XXXXX&orderAmount=30.0&orderCurrency=EUR&step=2&transactionId=76616886",`
(I hard coded the parameters `orderRef=XXXXX&orderAmount=30.0&orderCurrency=EUR&step=2`)

The payment page is using correctly my custom CSS styles, but there is not amount, neither currency in the page.

**Comment by felixhagspiel** [comment]
Hello @Riwak Riwak , It seems my template URL is ignored as well.

This is how I set the option:

		PayInTemplateURLOptions templateOptions = new PayInTemplateURLOptions();
		templateOptions.PAYLINEV2 = templateURL;
		exec.setTemplateURLOptions(templateOptions);
		payIn.setExecutionDetails(exec);

But in the response from mangopay I always get the default page and  template options are null:
![image](https://user-images.githubusercontent.com/5927172/77257509-3090f080-6c75-11ea-9843-aba60dc71edb.png)

Is there any way to check if my template is fine? Our URL match all requirements mentioned here: 
https://docs.mangopay.com/guide/customising-the-design

I can privately message you our payline URL if that is any help.

**Comment by mickaelpois** [comment]
Good afternoon everyone !

This new PAYLINEV2 parameter management highlight an old bug on serialization.
#183 will fix it, by deleting wrongly set `ExecutionDetails` property on JSON call, which made `TemplateURLOptions` object not well understood by our API (bug only visible for Payin Web)

A fix will be deployed this afternoon 🙏

**Comment by mickaelpois** [comment]
Release 2.10.1 is now available on maven @felixhagspiel.
