### ISSUE TITLE
NaturalUser IncomeRange not been handled correctly

### ISSUE THREAD

**Issue by stuslicer** [Mangopay/mangopay2-java-sdk#18]
Hello,

There appears to be problem with handling properties of type Integer, for example `UserNatural.IncomeRange`.

Looking at `RestTool` looks like the issue is the handling of the response for Integers, the code just checks for int.class rather than Integer (Double checks appears to do this correctly).
Consequence of this is the NaturalUser income range is not returned during gets.

Thanks,
Stuart

**Comment by hobailey** [comment]
Hi @stuslicer, sorry for the delay with this, but it's just been updated with da5ece7 :-)
