### ISSUE TITLE
BankAccountDeserializer is not null tolerant

### ISSUE THREAD

**Issue by kaczuss** [Mangopay/mangopay2-java-sdk#192]
`BankAccountDeserializer` is not null tolerant so the valid request with `BankAccount` object cannot be deserialized.

When I want to deserialize request for bank account creation where e.g. regarding to documentation `BIC` number for bank account details of `IBAN` type is optional I got `NullPointerException`.

```java
Caused by: java.lang.NullPointerException: null
	at com.mangopay.core.deserializer.BankAccountDeserializer.deserialize(BankAccountDeserializer.java:43)
	at com.mangopay.core.deserializer.BankAccountDeserializer.deserialize(BankAccountDeserializer.java:12)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)

```

I understand that you de-serialize only responses, but since requests and response use the same class deserializer, it should work for both cases. Please notice also that v2.01 documentation https://docs.mangopay.com/endpoints/v2.01/bank-accounts#e40_the-iban-bankaccount-object doesn't say in any place that `BIC` number is not optional for the response.

**Comment by SoloJr** [comment]
Hello @kaczuss. Can you provide your object (in any format, json if possible) in order to test on our side? Also, which type of BankAccount are you using?

**Comment by kaczuss** [comment]
Hi, this is sample request I send. I want to save it and later deserialize for testing purpose. As you can see I use `IBAN` bank account type.

```json
{
  "Id": "54321012",
  "CreationDate": 1579534200,
  "UserId": "99887766",
  "Type": "IBAN",
  "OwnerName": "Passenger 3 User",
  "OwnerAddress": {
    "AddressLine1": "Teststreet",
    "City": "Testcity",
    "PostalCode": "12345",
    "Country": "DE"
  },
  "IBAN": "FR7611808009101234567890147"
}
```

So if I run code on 
```java
new RestTool(api, false).castResponseToEntity(BankAccount.class, JsonParser.parseString("{\n" +
				"  \"Id\": \"54321012\",\n" +
				"  \"CreationDate\": 1579534200,\n" +
				"  \"UserId\": \"99887766\",\n" +
				"  \"Type\": \"IBAN\",\n" +
				"  \"OwnerName\": \"Passenger 3 User\",\n" +
				"  \"OwnerAddress\": {\n" +
				"    \"AddressLine1\": \"Teststreet\",\n" +
				"    \"City\": \"Testcity\",\n" +
				"    \"PostalCode\": \"12345\",\n" +
				"    \"Country\": \"DE\"\n" +
				"  },\n" +
				"  \"IBAN\": \"FR7611808009101234567890147\"\n" +
				"}").getAsJsonObject())
```
It fails with NPE

**Comment by SoloJr** [comment]
[See this branch](https://github.com/Mangopay/mangopay2-java-sdk/tree/hotfix/issue_192).

**Comment by mangomaxoasis** [comment]
Hi @kaczuss 
I am closing this issue for the time being, let us know if the issue persists
Max
