### ISSUE TITLE
Get wallet balance incorrect amount

### ISSUE THREAD

**Issue by smartum-vn** [Mangopay/mangopay2-java-sdk#194]
Hello, i think we need replace int to big int in Money.class  because I work with big sum and have problem use SDK. 

{"Description":"Wallet owner aliaksandr.t@smartum.pro","Owners":["79838220"],"Balance":{"Currency":"GBP","Amount":9447560941},"Currency":"GBP","FundsType":"DEFAULT","Id":"79838226","Tag":null,"CreationDate":1588664925}

![Безымянный](https://user-images.githubusercontent.com/42865574/81717561-5d969e00-9483-11ea-817c-66eddf5eb179.png)

**Comment by smartum-vn** [comment]
max int  2,147,483,647   but i need  9.447,560,941 and more

**Comment by mangomaxoasis** [comment]
Hi @smartum-vn 
Thanks for the question
At this time we are staying with int, as there are a number of repercussions on our side 
The switch to big is on our roadmap, has been requested by several people, but the rollout won't be in the short term 
We'll keep our community updated 
Cheers,
max
