### ISSUE TITLE
Need of Update

### ISSUE THREAD

**Issue by Rupiert** [Mangopay/mangopay2-java-sdk#198]
These lines are Deprecated. Hosted on:  [https://github.com/Mangopay/mangopay2-java-sdk](Deprecated Example) in the bottom.

`
    // get some user by id
    User john = api.Users.get(someId);

    // change and update some of his data
    john.Tag += " - CHANGED";
    api.Users.update(john);

    // get all users (with pagination)
    Pagination pagination = new Pagination(1, 8); // get 1st page, 8 items per page
    List<User> users = api.Users.getAll(pagination);`

**Comment by MuraruMihai** [comment]
@Rupiert can you please give us more info? We cannot find deprecated lines.

**Comment by SoloJr** [comment]
@Rupiert 

We updated that part of the README.md

Check [https://github.com/Mangopay/mangopay2-java-sdk/commit/26122efabac40015d24c980cde46066ed83ce612]
