### ISSUE TITLE
Regression in fix 203

### ISSUE THREAD

**Issue by ptroc** [Mangopay/mangopay2-java-sdk#205]
Sorry Mangopay, 
in my last fix there is bug.
Unfortunately there is a copy paste error in line: 
`payInExecutionDetailsBankingAlias.setBankingAliasId(object.get("WireReference").getAsString());`
it should be: 
`payInExecutionDetailsBankingAlias.setWireReference(object.get("WireReference").getAsString());`

https://gist.github.com/ptroc/014e07807c779ab573f03d553799daa5

**Comment by mangomaxoasis** [comment]
@ptroc OK we'll look into it

**Comment by mangomaxoasis** [comment]
Fix deployed
