### ISSUE TITLE
Please include UserId into UboDeclaration object

### ISSUE THREAD

**Issue by keiki85** [Mangopay/mangopay2-java-sdk#217]
Hi,

the com.mangopay.entities.UboDeclaration does not contain the "UserId", which is yet in the result of the "/kyc/ubodeclarations/{{UBO_DECLARATION_ID}}" call.

Without the user id it's difficult to trace back to the user. Can you please add this to the entity?

Thank you very much.

**Comment by mangomaxoasis** [comment]
Hi @keiki85 
We're looking into it

**Comment by mangomaxoasis** [comment]
Released
