### ISSUE TITLE
The getAll() method is very confusing

### ISSUE THREAD

**Issue by igortwago** [Mangopay/mangopay2-java-sdk#226]
The HookApiImpl class has the getAll() method. 
But this method doesn't return all hooks as its name can suggest, but it returns only first ten items. 
It is very confusing.

**Comment by tasosz** [comment]
@igortwago, the issue you raise is down to paging as used by the Mangopay APIs. The default page size is 10, which is what you are seeing (with max 100). The APIs also provide some info through response header data.
See here: https://docs.mangopay.com/guide/lists-pagination-management

**Comment by igortwago** [comment]
At least you can provide javadocs for this method. Because the name is not about the method at all.

**Comment by mangomaxoasis** [comment]
Hi @igortwago 
We'll try to review the javadocs soon
