### ISSUE TITLE
List preauthorizations for a user endpoint missing pagination and filter parameters in SDK 

### ISSUE THREAD

**Issue by tomBP** [Mangopay/mangopay2-java-sdk#232]
Hi, 

I'm one of the developers at Wallapop. We had originally contacted with Patricia Rodriguez but she asked that we raise an issue here.

We're running into a couple of limitations with the [list preauthorizations for a user](https://docs.mangopay.com/endpoints/v2.01/preauthorizations#e995_list-preauthorizations-for-a-user) enpoint. 

1. The endpoint seems to only return a maximum of 10 preauthorizations. I imagine this is due to pagination but, unlike other endpoints such as `getCards` or `getTransactions`, the SDK doesn't allow you to provide pagination or sorting. 
2. The docs imply that you can filter by `Status`, `ResultCode`, and `PaymentStatus` but again, the SDK doesn't allow you to provide these. 

Regards, 
Tom Pearson

**Comment by dduwoyemgp** [comment]
Hi @tomBP 
We're looking into it

**Comment by dduwoyemgp** [comment]
Thanks again @tomBP for you contribution.
We are quite aware of this difference of functional coverage between the SDK and the mentioned endpoint. We are working on an update to bridge this gap.

**Comment by tomBP** [comment]
Great, thanks @dduwoyemgp

**Comment by SoloJr** [comment]
Hi @tomBP 

I've added the PR with the needed methods. Can you take a look and tell us if there is anything more to add?

Thanks

**Comment by tomBP** [comment]
@SoloJr Looks good to me :)

**Comment by tomBP** [comment]
Hey! Any update on this?

**Comment by dduwoyemgp** [comment]
> Hey! Any update on this?

Hello @tomBP 
A new release is about to be deployed this week. We'll keep you informed :)

**Comment by tomBP** [comment]
Thanks @dduwoyemgp :)

**Comment by dduwoyemgp** [comment]
Hello @tomBP 
I invite you to have a look on the [new release](https://github.com/Mangopay/mangopay2-java-sdk/releases/tag/2.12.0) we've just deployed

**Comment by dduwoyemgp** [comment]
Hello @tomBP 
Can we close this issue following the [new release](https://github.com/Mangopay/mangopay2-java-sdk/releases/tag/2.12.0) we've just released
