### ISSUE TITLE
List transactions for a Mandate not available in the sdk

### ISSUE THREAD

**Issue by fupelaqu** [Mangopay/mangopay2-java-sdk#236]
I could not see the endpoint allowing to list the transactions for a mandate as defined here [list-transactions-for-a-mandate](https://docs.mangopay.com/endpoints/v2.01/transactions#e993_list-transactions-for-a-mandate)

**Comment by fredericdelordm** [comment]
Hello @fupelaqu,

We are having a look at this with the team.

Have a nice day,

**Comment by SoloJr** [comment]
Hi @fupelaqu 

Firstly, sorry for the late reply.
Secondly, the endpoint mentioned by you is already available: [here](https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/main/java/com/mangopay/core/APIs/implementation/MandateApiImpl.java#L81)

The presented endpoint corresponds to this: put("mandate_get_transactions", new String[]{"/mandates/%s/transactions", RequestType.GET.toString()}); - which is the same as the one from the mangopay documentation posted by you.

Kind regards,
SoloJr

**Comment by fredericdelordm** [comment]
Hello @fupelaqu,

Do you still have the issue ?

Have a nice day,
