### ISSUE TITLE
Parsable error

### ISSUE THREAD

**Issue by jonathan-bibas** [Mangopay/mangopay2-java-sdk#244]
Hi, is there any way to get an excpetion fit to mangopay exception way? My wish is a mean to detect when the error is a resource not found exception

**Comment by fredericdelordm** [comment]
Hello @jonathan-bibas,

Thank you for your suggestion. We are going to improve this.

Have a nice day,

**Comment by SoloJr** [comment]
Hi @jonathan-bibas 

There is already a custom class for exception handling [here](https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/main/java/com/mangopay/core/ResponseException.java) 

Do you feel the need for more? If so, can you please provide details?

Kind regards,
SoloJr
