### ISSUE TITLE
Release issues

### ISSUE THREAD

**Issue by ArnaudT** [Mangopay/mangopay2-java-sdk#25]
Hi,

I would like to upgrade the library in our project.

It's written on the the README that the SDK is published as a Maven artifact on jCenter.
When I check jCenter, the last release is v1.0.6 on the May 16th.
https://bintray.com/mangopay/mangopay2-java-sdk/mangopay2-java-sdk/v1.0.6/view

But on github the last release is v1.0.7 on Apr 12th. 
What version should I take? Should I trust github or jCenter to download the artifact?

It seems that there is an issue in https://github.com/Mangopay/mangopay2-java-sdk/blob/master/build.gradle#L53
It doesn't match the version of the application. 
https://github.com/Mangopay/mangopay2-java-sdk/blob/master/build.gradle#L22

When I try to build it myself (to deploy in our internal maven repository), I have 18 tests failures with the command `gradle test`
Is there any configuration to setup in order to run the tests?
<img width="716" alt="mangopay test failures" src="https://cloud.githubusercontent.com/assets/230992/15290311/f435381e-1b77-11e6-9168-6d21f92f112f.png">

How can I the last stable version?

Thanks for your help.

**Comment by hobailey** [comment]
Hi @ArnaudT, v1.0.7 is the latest (on Github), but we're in the process of adding the library to Bintray etc, so it's not quite all up to date yet.
As for the failing tests, are you running with your own `ClientId` or the one in the SDK?

**Comment by ArnaudT** [comment]
Thanks @hobailey.
I am using the default configuration from the sdk. 
I just run `gradle test`.

**Comment by hobailey** [comment]
Hmm, for the ones related to disputes it's normal they're failing since it requires various statuses etc for them all to pass. As for the others though, I'm not sure what's going on - are these results systematic?

**Comment by ArnaudT** [comment]
How can I can I know if a test that fail is normal or not?
I don't really think that tests that fail randomly are normal for a library like this.
The tests should create the various statuses to pass and have the same result at each run.

The result are not systematics.  :-$
second time 107 tests completed, 11 failed.
<img width="693" alt="test failures mp" src="https://cloud.githubusercontent.com/assets/230992/15293418/22457ab0-1b88-11e6-87bf-44a79b76e671.png">

Do you know when the v1.0.7 will be available in Bintray?

Thanks.

**Comment by ArnaudT** [comment]
Hi,

Thanks for releasing in bintray.
But I have few issues:
### There is a mismatch in the doc.
https://bintray.com/mangopay/mangopay2-java-sdk/mangopay2-java-sdk/v1.0.7/view#read

### We can not download the jar via maven
I follow what is written in the doc but it doesn't work:

`
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/mangopay/mangopay2-java-sdk/1.0.7/mangopay2-java-sdk-1.0.7.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.mangopay#mangopay2-java-sdk;1.0.7: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
`

The pom, file doesn't exist.
Thanks.

**Comment by hobailey** [comment]
Yep, thanks @ArnaudT - as discussed in #1, we're still (slowly) working on this maven/jCenter deployment.
As for the failing tests, you're right - it's not very helpful for developers, but it's finding a balance between being able to fully test the SDK and not being too much of a pain to run the tests. I'll get someone to look into why these tests are failing and remove the ones that have depencanies on other things (internally created objects like Disputes for example).

**Comment by Ziaccro** [comment]
Hi there,

i have also an issue to get the current version in bintray

https://bintray.com/mangopay/mangopay2-java-sdk/mangopay2-java-sdk/v1.0.6/view#read

same error as ArnaudT but with the version 1.0.6

**Comment by hobailey** [comment]
Hey everyone, the unit tests are now working systematically, and as per my comment on #1, the issues with Bintray are fixed too :-)
