### ISSUE TITLE
SDK : X-Number-Of-Items & X-Number-Of-Pages 

### ISSUE THREAD

**Issue by SylvainAssemat** [Mangopay/mangopay2-java-sdk#253]
Hi all 

Is there any way to find out those 2 headers below within the JAVA SDK (2.16) ?
I don't see this feature on the public road map (trello)

_X-Number-Of-Items In the header X-Number-Of-Item you can read the number of items in the entire list.
X-Number-Of-Pages In the header X-Number-Of-Pages you can read the number of pages in the entire list._

I can get them using a call HTTP (without using the SDK), but it will increase the rate limit counter ... i suppose
It 's a little confusing.

Maybe adding a "count" REST API without using the headers could be a better way to go ?

Thanks for your help

**Comment by fredericdelordm** [comment]
Hello @SylvainAssemat,

The SDK returns the following headers :
 - x-ratelimit
 - x-ratelimit-remaining
 - x-ratelimit-reset
 
 Does this solve your issue?

**Comment by SylvainAssemat** [comment]
Hi @fredericdelordm 

I' am talking about X-Number-Of-Items /  X-Number-Of-Pages 
And you answer me about X-RateLimit ?

Obvisouly it can not solve anything.

As you closed this issue without any reason, no need to go further.

**Comment by fredericdelordm** [comment]
Sorry @SylvainAssemat,

You are normally able to access those headers with the SDK. I will double check how with the tech team.

**Comment by SoloJr** [comment]
Hi @SylvainAssemat 

The API returns the headers you are mentioning. Each response the sdk gets from the api, gets deserialized, and the headers are read. You can find them only if you use the pagination options, as they are set there. You can find the properties "totalPages" and "totalItems" helpful [see here](https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/main/java/com/mangopay/core/Pagination.java)
