### ISSUE TITLE
Making Payment

### ISSUE THREAD

**Issue by SonicxPrime** [Mangopay/mangopay2-java-sdk#255]
Hello,

Can this SDK perform payment. I was looking for this kind of example but found nothing.

Thanks in advance,
Regards,
SonicxPrime

**Comment by fredericdelordm** [comment]
Hello @SonicxPrime ,

Yes this SDK can perform payment. You have some examples here : [](https://github.com/Mangopay/mangopay2-java-sdk/tree/master/src/test/java/com/mangopay)
