### ISSUE TITLE
RecurringPayInMIT lacks getters and setters 

### ISSUE THREAD

**Issue by igorlash** [Mangopay/mangopay2-java-sdk#257]
com.mangopay.entities.RecurringPayInMIT doesn't have getters and setters for the debitedFunds and fees private fields.

**Comment by fredericdelordm** [comment]
Hello @igorlash,

We are planning to release them soon.

**Comment by igorlash** [comment]
Hello @fredericdelordm 
I am working now on recurring payments, and I need to plan a next release. @fredericdelordm  could you be more specific when you are going to release?
