### ISSUE TITLE
Idempotency.get doesn't seem to work

### ISSUE THREAD

**Issue by ArnaudT** [Mangopay/mangopay2-java-sdk#26]
Hi,

I have multiple issues with `Idempotency.get`. I can not make it work on the sandbox environment.

### Idempotency.get("")
When the string is empty we have this weird error instead of a 404 I suppose.
```{"Message":"No HTTP resource was found that matches the request URI 'https://api.sandbox.mangopay.com/v2.01/XXXXX/responses/'."} (MangoPayApi.scala:160)```

### Idempotency.get("77nurmc5up7vl8i9rkfnggtc30")
When I try to get an existing key I have the following message:
```java.lang.IllegalStateException: Not a JSON Object: null (JsonElement.java:90)
com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
com.mangopay.core.RestTool.checkResponseCode(RestTool.java:974)```

Do you know what is the problem?

Thanks for your help.

**Comment by hobailey** [comment]
Hey @ArnaudT, I've just run the [unit test](https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/test/java/com/mangopay/core/ApiIdempotencyTest.java) and this does seem to be working correctly - have you had a quick check at this for a example?

**Comment by ArnaudT** [comment]
Do I have to use a specific version of the lib?
I am using one from Mars 22th.

I have issues when I run the tests:
https://github.com/Mangopay/mangopay2-java-sdk/issues/25
Do I have to do anything special?

**Comment by hobailey** [comment]
Nothing special, nor a particular release no - is even the unit test failing for you?

**Comment by ArnaudT** [comment]
The ApiIdempotencyTest works fine.

What does mean the error `java.lang.IllegalStateException: Not a JSON Object: null (JsonElement.java:90)`? 
The response is not valid. Even if the key was not found I do not understand with the lib crash. 
Do you have more information on your side?

Thanks.

**Comment by hobailey** [comment]
Hmm, strange - could you let me know your sandbox ClientId and the datetime of when you had the problem please?

**Comment by ArnaudT** [comment]
sent to support@mangopay.com.
Thanks.

**Comment by hobailey** [comment]
OK, thanks. Let's continue the discussion there.
