### ISSUE TITLE
Instant payout EventTypes are missing

### ISSUE THREAD

**Issue by keiki85** [Mangopay/mangopay2-java-sdk#263]
Hello,

I saw that for your most recent release Primrose you are missing the new EventTypes

INSTANT_PAYOUT_SUCCEEDED
INSTANT_PAYOUT_FALLBACKED

Can you please provide them?

Thank you very much

**Comment by fredericdelordm** [comment]
Hello @keiki85,

They are planned for the next release. I'll keep you updated

**Comment by keiki85** [comment]
Wow that was chat like fast. Thank you very much :-)

**Comment by keiki85** [comment]
Any update please?

**Comment by fredericdelordm** [comment]
Hello @keiki85,

The release is planned this week. I'll write you a message when it's done.
