### ISSUE TITLE
Can't GET RecurringPayIn

### ISSUE THREAD

**Issue by AlexandreMoray** [Mangopay/mangopay2-java-sdk#269]
Hello,

During the CIT process, after 3DS validation, I need to get the `RecurringPayIn` object using the `transactionId` parameter that was injected in the `secureModeReturnUrl`. This is mandatory to get the CIT PayIn `recurringPayinRegistrationId ` and then get the recurringPayment for that id to check that its status is valid.

However, in the SDK apis, the only method that returns a `RecurringPayIn` object is `createRecurringPayInCIT` on creation, but there is no get request implemented to retieve it later. I've tried to use the normal `mangoPayApi.getPayInApi().get(id)` method but was not able to cast it to a RecurringPayIn subtype (class com.mangopay.entities.PayIn cannot be cast to class com.mangopay.entities.RecurringPayIn).

Without it, I can't achieve last step of the registration to retrieve the RecurringPayment et save its paymentMean in our database.

It is a missing feature of the SDK ? I was not able to find any implemented test related to this need in the repository.

Is there another way to complete this ? (It corresponds to the two steps starting at 5:04 in [your tutorial video](https://youtu.be/Bwe4u08CH84))

Thank you

**Comment by SoloJr** [comment]
Hi @AlexandreMoray 

Please take a look [here](https://github.com/Mangopay/mangopay2-java-sdk/blob/master/src/test/java/com/mangopay/core/PayInApiImplTest.java#L718) 

This may solve your issue. You are right, the class to get a ReccuringPayIn is **RecurringPaymentExtended**

Try with this and tell me if it worked. If not, we'll implement the needed changes right away.

**Comment by AlexandreMoray** [comment]
Hi @SoloJr,

Thank you for your response.

It looks that piece of code you refer to is used to get a RecurringPayment from its id.

My need comes before that, at a step where the only information I've got is the id of the CIT PayIn, what I need is to get the `ReccuringPayIn` from that id to obtain the id of the `recurringPayment` and then fetch it like shown in your link.

**Comment by SoloJr** [comment]
Hi @AlexandreMoray 

I got you. Fix pushed [here](https://github.com/Mangopay/mangopay2-java-sdk/pull/270)

It will be released soon, maximum two days. :) 

Thanks

**Comment by AlexandreMoray** [comment]
Thank you @SoloJr !

I'm waiting for the release :)
