### ISSUE TITLE
Deserialization UBO

### ISSUE THREAD

**Issue by SylvainAssemat** [Mangopay/mangopay2-java-sdk#271]
Hi

I have a question (maybe an issue) about how to deal with the Ubo object.
I create an UBO and i use the "tag" attribute with a custom data.
The creation is OK

However, when i try to get back the Ubo , i don't see any TAG attribute back in the object, and so can not access the previous custom data.

Is it a normal behaviour ?

**Comment by fredericdelordm** [comment]
Hello @SylvainAssemat,

Sorry for the late reply. 

Our API ignores the tag added to the UBO. It's not a bug. Would you want to add a tag to your UBO? What is your usecase? I will share it with the API team.

Have a nice day,

**Comment by SylvainAssemat** [comment]
Hi

For example we use the tag to send th amount of pourcent of part (like 25% ...) 
As the UBO have a setter for the tag attribute, it should be logic to get the value too when the deserialization is processing.

It could be useful to add a _List<String, Object>_ in all of your model (even limited size), to pass any **metadata** that could be useful out of mangopay (id, key, flag, etc...) to avoid this kind of behaviour, i mean :  finding a way to pass contextual data.

**Comment by fredericdelordm** [comment]
Ok @SylvainAssemat, I'll share the information with the team.

**Comment by SylvainAssemat** [comment]
Hi 

Any news on this issue ?

Thanks

**Comment by fredericdelordm** [comment]
Hi @SylvainAssemat,

It is not supported yet by the API and therefore cannot be added in the SDK. I will keep you up to date, if it change.

Have a nice day,

**Comment by SylvainAssemat** [comment]
It's supporting on other model object.
Dont understand since December i have opened this issue, why it s seems so difficult to do so on the UBO object.
Having an attribute without possibility of using it is clearly an issue by design.
