### ISSUE TITLE
NPE when platform is down

### ISSUE THREAD

**Issue by sahbi-ktifa** [Mangopay/mangopay2-java-sdk#288]
Hello, 
I'm working at Malt and working with the MangoPay SDK for few years now.
I've noticed lately that every time you're having a problem on your platform, we're impacted because the connection does not seem properly handled.

We received NullPointerException at src/main/java/com/mangopay/core/RestTool.java:391

```
            InputStream is;
            if (this.responseCode != 200 && this.responseCode != 204) {
                is = connection.getErrorStream();
            } else {
                is = connection.getInputStream();
            }

            StringBuffer resp;
            try (BufferedReader rd = new BufferedReader(new InputStreamReader(is, "UTF-8"))) {
                String line;
                resp = new StringBuffer();
                while ((line = rd.readLine()) != null) {
                    resp.append(line);
                }
            }
```

The thing is, in that code,  `connection.getInputStream();` could be null, therefore triggers a NPE.

Could you have a look at that issue please and let us know? 🙏

**Comment by fredericdelordm** [comment]
Hello @sahbi-ktifa, it has been fixed in the latest release
