### ISSUE TITLE
Cannot resolve maven dependency

### ISSUE THREAD

**Issue by catacraciun** [Mangopay/mangopay2-java-sdk#29]
I want to replace the jar dependency with the configured bintray dependency (from here https://bintray.com/mangopay/mangopay2-java-sdk/mangopay2-java-sdk). But there are some issues:
1. The POM dependency type is wrong, it must be JAR
2. Maven cannot resolve the dependency (which makes sense, as it resolves, by default, from Maven central repository). Unfortunately, I couldn't find any information on Bintray with the repository URL.

I want to avoid adding some global maven configuration (in settings.xml). I want everything to be added to the project pom.xml.

Maybe I am missing something, and everything is correct. But please let me know how can I configure this.

Thanks!

**Comment by catacraciun** [comment]
Ok, I found a 'tiny' url on bintray page: https://dl.bintray.com/mangopay/mangopay2-java-sdk/ 
This can be used as repository. So the final working pom.xml is the following (should be added into readme file also):

```xml
<dependencies>
    <dependency>
        <groupId>com.mangopay</groupId>
        <artifactId>mangopay2-java-sdk</artifactId>
        <version>1.1.0</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>mangopay-bintray</id>
        <url>https://dl.bintray.com/mangopay/mangopay2-java-sdk/</url>
        <releases>true</releases>
        <snapshots>false</snapshots>
    </repository>
</repositories>
```

**Comment by hobailey** [comment]
Relates to #31

**Comment by crisp2u** [comment]
Guys, I'm seeing the wrong  maven-metadata.xml here https://dl.bintray.com/mangopay/mangopay2-java-sdk. It looks like is the one from the android sdk package. Is this correct ? My nexus cannot read from this repo and I believe this is the issue

**Comment by catacraciun** [comment]
Hello @crisp2u, I have changed the repository with the general jcenter repository. Please check the new README file.

Cheers!

**Comment by hobailey** [comment]
@crisp2u there was a problem with the Bintray package organisation but it should be fine now :-)
Sorry for the delay getting back to you on that.
