### ISSUE TITLE
Allow CardApi to be overridden within tests

### ISSUE THREAD

**Issue by sahbi-ktifa** [Mangopay/mangopay2-java-sdk#316]
Hello,

Would it possible to modify the visibility of the setter "setCardApi" in `com.mangopay.MangoPayApi`?
Others APIs (wallet, user, ...) have their setters public, making them possible to override within our own test implementation.

Thank you for the answer

**Comment by fredericdelordm** [comment]
Hello @sahbi-ktifa,

We are looking into it.

**Comment by sahbi-ktifa** [comment]
Upgraded to 2.35.0 and now all methods are public, good job.
