### ISSUE TITLE
How to transfer money to client's wallet?

### ISSUE THREAD

**Issue by s101d1** [Mangopay/mangopay2-java-sdk#32]
I would like to transfer money from a mangopay user's wallet to platform owner or client's wallet.

I tried this way but it doesn't work:

	Wallet clientWallet = mangopayApi.Clients.getWallet(FundsType.FEES, CurrencyIso.GBP);
	
	Transfer transfer = new Transfer();
	transfer.AuthorId = mangopayUserId;
	transfer.DebitedWalletId = userWalletId;
	transfer.CreditedWalletId = clientWallet.Id;
	...
	mangopayApi.Transfers.create(transfer);

I got ResponseException with message `"CreditedWalletId":"Wallet not found"`. It seems client wallet Id can't be used.

What is the correct way to transfer money from user wallet to client wallet? Should I use a normal wallet instead?

**Comment by hobailey** [comment]
Hi @s101d1 - it is infact not possible to add funds to your Fees wallet in this way. The only option is to use the `Fees` parameter when doing transfers/payments. If you wish to discuss a certain use case, I suggest you write to support@mangopay.com with your `ClientId` and detailing more about your usecase :-)

**Comment by s101d1** [comment]
My use case is simple, I want the user to pay me everytime they do certain action. So it's between user and me (as platform owner), not between user and user. Is it still possible in mangopay?

**Comment by hobailey** [comment]
I suggest you discuss with our support by email on the best way to set this up please :-)
