### ISSUE TITLE
Wrong use of the coding conventions

### ISSUE THREAD

**Issue by bobonaut** [Mangopay/mangopay2-java-sdk#37]
Dear Mangopay developers,

Every entity you are using in the SDK does not follow the Oracle coding conventions.
See: http://www.oracle.com/technetwork/java/codeconventions-135099.html

Another thing is that every entity is using a public variable without accessors (getters and setters).
Is this a deliberate choice? Or is this how the SDK is compiled from another language?

If it is compiled from another language, could you please configure the project that it follows the standard guidelines of Java.

Kind regards,

bobonaut

**Comment by blackleg** [comment]
:+1:

**Comment by hobailey** [comment]
OK, thanks for flagging this up - we'll work on this and update the repo where possible (avoiding breaking changes of course).

**Comment by hobailey** [comment]
Quick update on this - we recently pushed some updates with no breaking changes. We're now working on an updated version of the SDK which will need to include some breaking changes, however it will make it confirm to conventions at least :-)

**Comment by moni8909** [comment]
Would be a good idea to also add builders to objects with lots of properties..

**Comment by mickaelpois** [comment]
Hello everybody !
Quick update about this: we have a pull request related to this: #54 
It is a first clean of this sdk with no breaking changes.
Then a second step will be done ASAP in order to tidy up a little more, but with breaking changes.

We will inform you about following updates 👍

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Coding conventions aren't respected](https://trello.com/c/eRtGVwjq/103-coding-conventions-aren-t-respected)

**Comment by mickaelpois** [comment]
Hi @bobonaut @blackleg @moni8909, here is our second and final step of Java SDK refactoring (see PR #68).
Feel free to give us your feedback / do a quick review about it this week: if everything is OK, it will be merged and released as a new 2.0 major release.

Thanks !

**Comment by bobonaut** [comment]
Hi @mickaelpois,
This is definitely a major improvement Keep up the good work!!!

Bobonaut
