### ISSUE TITLE
The test are failing

### ISSUE THREAD

**Issue by blackleg** [Mangopay/mangopay2-java-sdk#39]
com.mangopay.core.ApiClientsTest > test_ClientsCreateClient FAILED
    com.mangopay.core.ResponseException at ApiClientsTest.java:27

https://travis-ci.org/Mangopay/mangopay2-java-sdk

**Comment by hobailey** [comment]
Yes, this is due to some recent changes in the API and we haven't yet updated the SDK but we'll be doing this soon. 
In the meantime, there are no other impacts on the SDK/API :-)

**Comment by hobailey** [comment]
This has since been resolved and all tests are now passing :-)
