### ISSUE TITLE
Add GB Bank Account (not working)

### ISSUE THREAD

**Issue by lewisbarber** [Mangopay/mangopay2-java-sdk#41]
Adding a GB bank account currently fails with the new SDK. I have submitted a screenshot via your contact page. Here is the exception (it's not very informative):

{"Message":"Internal Server Error","Type":"other","Id":"d989139b-4980-42b8-85de-78af8a1a1cab#1476906932","Date":1476906933.0,"errors":null}

**Edit:** This occurs whilst using the sandbox

**Comment by hobailey** [comment]
Hi there, this is actually a known issue with our banking supplier I'm afraid. It is only affecting sandbox though. We'd don't yet have an estimated fix date unfortunately :-(

**Comment by hobailey** [comment]
I'm closing this ticket since it's non-SDK related. You can follow https://github.com/Mangopay/mangopay/issues/34 for updates.
