### ISSUE TITLE
v1.2.0 not found from jcenter

### ISSUE THREAD

**Issue by chrissom** [Mangopay/mangopay2-java-sdk#42]
Tried to fetch the v1.2.0 from jcenter but doesn't work. [Last version available is 1.1.2 from jcenter](http://jcenter.bintray.com/com/mangopay/mangopay2-java-sdk/).

**Comment by hobailey** [comment]
Hey @chrissom, looks like jCenter requires a Sonatype username to continue deploying (which seems like a new requirement since we last updated jCenter). I've submitted a request to them and will let you know once we're able to move forward :-)

**Comment by chrissom** [comment]
Good 👍 Keep me in touch when v1.2.0 gets available.

**Comment by hobailey** [comment]
I don't suppose you know how to create a Sonatype username do you?! It's not something we've done before and it's not clear how you supposed to...

**Comment by blackleg** [comment]
![Create a JIRA account in sonatype.org and open new ticket to create a project](http://central.sonatype.org/pages/ossrh-guide.html)

**Comment by chrissom** [comment]
Agreed, it's not obvious. Here's [the how to start](http://central.sonatype.org/pages/ossrh-guide.html).

Basically, you have to create a JIRA account and submit a ticket. After that, ping Sonatype by email or Twitter, to validate your ticket faster.

@blackleg your image link is broken.

**Comment by hobailey** [comment]
Yep, thanks @chrissom. Already on it :-) And have updated Bintray but Sonatype saying it's not working correctly. Anyway, we're working it - sorry for the delay!

**Comment by hobailey** [comment]
@chrissom we're getting a "Invalid pom path mangopay2-java-sdk-1.2.0.pom" error when syncing from Bintray to Sonatype. The POM file is [here](https://bintray.com/mangopay/mangopay2-java-sdk/download_file?file_path=mangopay2-java-sdk-1.2.0.pom) - I can't see anything wrong (and nor can Sonatype) but if you've done this before and see something incorrect, do let us know :-)

**Comment by hobailey** [comment]
I guess we should add the `developers` section but that doesn't seem to particularly tally with the error...

**Comment by chrissom** [comment]
@hobailey hard to help at this step without getting access to all details. Looks like it's not a big issue.

**Comment by blackleg** [comment]
@hobailey Check developer email start tag:
```
<developers>
	    <developer>
	      <name>Hugo Bailey</name>
	      <id>mangopay</email>
	    </developer>
	  </developers>
```

**Comment by hobailey** [comment]
I already fixed that, but no luck :-( Could I have one of your Bintray usernames to add you for you to take a look do you think?

**Comment by chrissom** [comment]
@hobailey Did you get some help from your Sonatype issue?

**Comment by hobailey** [comment]
They're not too helpful unfortunately (here's [the ticket](https://issues.sonatype.org/browse/OSSRH-26167)) but the say the POM file "looks fine". Will try and take another look at this today.

**Comment by blackleg** [comment]
I have this library: [Java Utilities](https://github.com/blackleg/java-utilities/blob/master/pom.xml) published in sonatype.
Probably you need add the javadoc and sign the library before deploy it in Bintray.

I think it is better that you deploy it directly to Sonatype.

**Comment by hobailey** [comment]
Hey quick update - we're still working on this, and it hasn't been forgotten, I promise :-)
(There's just been quite a few changes to jCentral since our last version release so it's taking a while to get in line on our side)

**Comment by chrissom** [comment]
Any news @hobailey? 

Btw, I tried to build the code (tag v1.2.0) and got 1 error during tests:

```
Failed tests:   Test_Reports_All(com.mangopay.core.ApiReportsTest): expected:<1785265[7]> but was:<1785265[5]>
```

Is it critical? I would like to use this local jar meanwhile you are fixing this issue?

**Comment by hobailey** [comment]
Hey @chrissom, it should now be deployed, yes. We're going to update the readme and a few bits in this repo tomorrow. 
As for that failing test, it's nothing serious (and a problem with the test implementation, rather than the API).

**Comment by chrissom** [comment]
Nice 👍  I close the issue.

**Comment by hobailey** [comment]
Great, thanks for the feedback, and sorry again that it took a while to get there.
