### ISSUE TITLE
Contest deadline date is never set

### ISSUE THREAD

**Issue by WardStinissen** [Mangopay/mangopay2-java-sdk#51]
Hi mangopay developers,

I am currently using your API for a client. 

When I was testing the hooks for a dispute, I noticed that the Contest deadline date is always 'null'. 

After a little debugging, I found that in com.mangopay.core.RestTool.java (line 747) there is a little bug. 

`if (fieldTypeName.equals(long.class.getName())) {
       f.setLong(result, entry.getValue().getAsLong());
 }`

In the code above, you check for the primitive 'long' but there should be a check for a Long Object instead. As the primitive 'long' is not found, the Contest deadline date is never set.

This is an urgent issue for our application. Could this please be fixed as soon as possible? 

Thanks you all for this great API!

**Comment by hobailey** [comment]
Hey @WardStinissen, thanks for flagging this up. Would you be able to do a pull request with the fix? This would be the quickest way to get it resolved, but if not we'll get it sorted as soon as we can :-)

**Comment by hobailey** [comment]
Hey, just to let you know that this has now been fixed with https://github.com/Mangopay/mangopay2-java-sdk/commit/3a523f6e8ae4e1c5dabfbcaaa8288a5a6b2f57af

**Comment by WardStinissen** [comment]
@hobailey Thanks for the fast fix of this issue! :-)
