### ISSUE TITLE
Rate limits headers for the response are lost and there is no way to get them

### ISSUE THREAD

**Issue by bonelli** [Mangopay/mangopay2-java-sdk#53]
RestTool class does't check for response headers `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset`
These are the main tools a developer can use to throttle requests when performing batch operations.

Is it possible to save these info when we get a response back from MangoPay's API?

**Comment by mickaelpois** [comment]
Hello @bonelli, sorry for the delay !
We will investigate about what happens with custom headers values, it seems to be an issue, you're right.
We will provide you an update as soon as we know more about that, sorry for the inconvenience.

**Comment by paulhristea** [comment]
Requesting more detail on the issue. Thanks

**Comment by gabriellupu** [comment]
I noticed that the API is returning the following values for rate limit headers:
```
{
    "x-ratelimit": "2, 5, 9, 5280",
    "x-ratelimit-remaining": "2298, 4495, 8791, 100320",
    "x-ratelimit-reset": "1490181540, 1490182440, 1490184240, 1490266980",
}
```
According to https://docs.mangopay.com/guide/rate-limiting

> For any API call, you’ll see some useful information in the response headers specifying:
* how many calls you’re allowed (`X-RateLimit-Limit`)
* how many you have left (`X-RateLimit-Remaining`)
* the time until these will be reset (`X-RateLimit-Reset`) In each case, several values will be given, separated by a comma - these correspond to each rate limit bucket (there are currently three - see the table above).

I think we need to better understand first why are the header values expressed as a lists. Thanks!

**Comment by paulhristea** [comment]
Seems to me that "x-ratelimit" (this is not "x-ratelimit-limit") is counting requests instead of simply declaring the maximum number allowed. So in the 15 minute timeframe, 2 requests have already been made, leaving "x-ratelimit-remaining" = 2298, which is the 15-minute limit of 2300 minus 2. Same goes for the second and third buckets.
Reaching a rate limit should result in 403 Forbidden responses until the "x-ratelimit-reset" happens.
As for the fourth column of values, I'm baffled.

**Comment by gabriellupu** [comment]
@paulhristea is there any way the java SDK consumers can read these header values?

**Comment by paulhristea** [comment]
Not currently, as far as I can tell. There is a method that takes care of response header data, but right now only 'Link' and pagination-related headers are being handled.

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add rate limit headers to SDK](https://trello.com/c/zK1rIyly/143-add-rate-limit-headers-to-sdk)

**Comment by mickaelpois** [comment]
This PR #76 will solve your issue @bonelli (I hope so !)
It will be released in the coming days !
