### ISSUE TITLE
NPE in ApiUsers.updateKycDocument

### ISSUE THREAD

**Issue by hlassiege** [Mangopay/mangopay2-java-sdk#55]
Hi,

We have a NPE when receiving the response of an API call : 

```
java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at com.mangopay.core.RestTool.doRequest(RestTool.java:400)
	at com.mangopay.core.RestTool.request(RestTool.java:142)
	at com.mangopay.core.APIs.ApiBase.updateObject(ApiBase.java:435)
	at com.mangopay.core.APIs.ApiBase.updateObject(ApiBase.java:406)
	at com.mangopay.core.APIs.ApiUsers.updateKycDocument(ApiUsers.java:343)
	at com.hopwork.notifier.compliance.MangoKYCFileHandler.sendKycDocument(MangoKYCFileHandler.java:216)
	at com.hopwork.notifier.compliance.MangoKYCFileHandler.complianceFileValidated(MangoKYCFileHandler.java:148)
```

This is for the API : /users/{USER_iD}/KYC/documents/{DOCUMENT_ID}   (PUT)

it seems to be located here : 
``` 
            // get response
            this._responseCode = _connection.getResponseCode();
            InputStream is;
            if (this._responseCode != 200 && this._responseCode != 204) {
                is = _connection.getErrorStream();
            } else {
                is = _connection.getInputStream();
            }

            StringBuffer resp;
            try (BufferedReader rd = new BufferedReader(new InputStreamReader(is, "UTF-8"))) {
                String line;
                resp = new StringBuffer();
                while ((line = rd.readLine()) != null) {
                    resp.append(line);
                }
            }
```

The symptom, "is" is null. We know that the api calls are successfull because the kyc document is correct on the mangopay dashboard.
So we can only suppose that it's null because this._responseCode is neither 200 nor 204 but getErrorStream return null.

**Comment by hobailey** [comment]
Hey @hlassiege, could you confirm what version of Java and which SDK version you're using? And also, could you confirm what happens when you run the SDK unit tests?

**Comment by hlassiege** [comment]
We are using java 1.8 and SDK 1.2.3.

**Comment by hobailey** [comment]
OK, thanks. After further investigation, it seems likely that there has infact been an impact to Java clients following our API update yesterday morning. We're looking into this asap and will update you shortly :-)

**Comment by hlassiege** [comment]
Could you give us an update today ?

**Comment by hobailey** [comment]
Hey @hlassiege, I'm afraid we still haven't been able to see where this is coming from, but we have been investigating all day. We'll provide another update tomorrow or as soon as we know more.

**Comment by eusuntpetri** [comment]
Problem seems to be in the back-end.

On the Java SDK, I ran a test which at one point calls 'https://api-test.mangopay.com/v2.01/sdk-unit-tests/users/2835270/KYC/documents/2835271' with the necessary data, but the HTTP status line (first header line) which should be something like 'HTTP/1.1 200 OK' or 'HTTP/1.1 204 No Content' is read as 'unknown/unknown'.

Should be a short debugging session on the server to pinpoint the problem, as it's quite major.

**Comment by hlassiege** [comment]
Hi, do you have some news about this problem ?

**Comment by marinehda** [comment]
Hey @hlassiege , we've just identified the rootcause. We have an issue with our logging on 204 response code. This will be fixed on Tuesday, Jan 24 at the latest. In the meantime the KYC doc workflow is actually working: you can still create a doc, upload a page and update the doc.
We apologize for the inconvenience.

**Comment by hlassiege** [comment]
I wouldn't say the workflow is working. The update fails on our site because of this NPE. So from our perspective, every update is failing and we don't know if it's for a "regular" reason or if this is really failing. 
So from our side, all documents are in error. 
We will have to browse every documents since the 17 and check if this is ok on the mangopay dashboard and update our data in our database.

So, I won't say the workflow is working. And the consequence for us are important.

**Comment by marinehda** [comment]
Indeed in the meantime you can check on the Mangopay Dashboard and if you need any additional check, feel free to contact support@mangopay.com. We know that it is time consuming for you and we apologize for this. Please be assured that this fix is our top priority.

**Comment by hlassiege** [comment]
any news ?

**Comment by hlassiege** [comment]
any news ?

**Comment by marinehda** [comment]
The issue has been fixed
