### ISSUE TITLE
RestTool doesn't release connections when dropped.

### ISSUE THREAD

**Issue by bartboogaerts** [Mangopay/mangopay2-java-sdk#62]
When connections/sockets are dropped, the api doesn't release the connection and keeps on waiting forever.
This results in calls to mango e.g. MangoPayApi.Users.get(id) begin stuck forever.

It would be nice to have a working timeout functionality.

**Comment by mickaelpois** [comment]
Hello @bartboogaerts,

Thanks for your feedback.
We're supposed to have a built-in timeout value, let us check if everything works well ASAP.
If you have any code snippet to bring us, feel free to post it there, it will be helpful !

Mickaël

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug? - Connection not released](https://trello.com/c/c8KNuDnt/163-bug-connection-not-released)

**Comment by mickaelpois** [comment]
Dear @bartboogaerts 
It seems that our tests are OK with timeout.
Maybe have you changed some configuration that erase built-in timeout value?
If you have any snippet of code or configuration file to share (if this issue is always existing on your side) it could be helpful.

**Comment by bartboogaerts** [comment]
Dear Mickaël,

 

We’ve changed nothing on our side…

Using the sdk in most simple way…

 

Can you then point me to the concrete tests you did about timeout?

 

Thanks, Bart
