### ISSUE TITLE
Wallet retrieving error

### ISSUE THREAD

**Issue by leloupnicolas** [Mangopay/mangopay2-java-sdk#63]
I encounter an issue using the SDK with an Android app.

I try to retrieve a Wallet by its ID, using the `.Wallets.get("")` but it makes my app crash with the following logs:
`System.err: com.mangopay.core.ResponseException: {"Message":"The requested resource does not support http method 'POST'."}`

Anyone having the same issue?

**Comment by mickaelpois** [comment]
Hello @leloupnicolas !

Could you give us a full code snippet in order to analyse your issue ? It will be helpful.

Thnaks a lot !

**Comment by leloupnicolas** [comment]
Hi @mickaelpois,

Thanks for your answer.

The following class is my own MangoPay service helper:
```java
// MangoPayService.java
public class MangoPayService {
    private static final String CLIENT_ID = "";
    private static final String CLIENT_PWD = "";
    private static final String CLIENT_URL = "https://api.sandbox.mangopay.com";
    private final MangoPayApi api;
    public MangoPayService() {
        api = new MangoPayApi();
        // configuration
        api.Config.ClientId = CLIENT_ID;
        api.Config.ClientPassword = CLIENT_PWD;
        api.Config.BaseUrl = CLIENT_URL;
    }
    public MangoPayApi getApiInstance() {
        return api;
    }
    public void getWalletAsync(GetWalletAsyncTask task, String walletId) {
        task.execute(walletId);
    }
}
```

This one is a custom AsyncTask dedicated to the Wallets retrieving:
```java
// GetWalletAsyncTask.java
public class GetWalletAsyncTask extends AsyncTask<String, Integer, Wallet[]> {

    private MangoPayApi api;

    public GetWalletAsyncTask(MangoPayApi api) {
        this.api = api;
    }

    @Override
    protected Wallet[] doInBackground(String... params) {
        int count = params.length;
        Wallet[] wallets = new Wallet[count];
        for (int i = 0; i < count; i++) {
            try {
                wallets[i] = api.Wallets.get(params[i]);
            } catch (Exception e) {
                e.printStackTrace();
            }
            publishProgress((int) ((i / (float) count) * 100));
            if (isCancelled()) {
                break;
            }
        }
        return wallets;
    }
    
    @Override
    protected void onPostExecute(Wallet[] wallets) {
        super.onPostExecute(wallets);
        if (wallets != null && wallets.length > 0) {
            wallet = wallets[0];
            if (wallet != null) {
                Money balance = wallet.Balance;
                String amount = String.format(Locale.getDefault(), "%.2f", (float) (balance.Amount / 100)) + "€";
                System.out.println(amount);
            }
        }
    }       
}
```

And, here is the main part of code:
```java
// SomeActivity.java
String walletId = userManager.getCurrentUser().getMangoPayWalletId();
MangoPayService mangoPayService = new MangoPayService();
mangoPayService.getWalletAsync(new GetWalletAsyncTask(mangoPayService.getApiInstance()), walletId);
```

Thanks!

**Comment by mickaelpois** [comment]
@leloupnicolas,

Thanks for your code.
Unfortunately, it is a known issue on our side, especially with Android.

Our SDK is not a multi-treaded oriented-one yet, so you can't call our API as you've done it. 
I suppose that you're doing some creation action after trying to get a wallet, and that is the reason why you GET action is not tried as a GET but as a POST method. 

We are really sorry about this issue, and we will try to improve the way our SDK is done ASAP (make our variables thread-safe and every related updates in order to manage multi-thread implementations).

Mickaël

**Comment by leloupnicolas** [comment]
@mickaelpois thanks for your reply and the info about multi-threading.

I'm not doing any creation after the wallet retrieving.

Also, I don't think encapsulating the call inside an AsyncTask should change the HTTP method used to retrieve a wallet. What do you think about this idea?

FYI I tried to use the SDK in a Blank Android App, and I got the same issue, using synchronous or asynchronous ways to retrieve wallets. Are you sure your SDK is usable for Android purposes (networking on main thread is forbidden on Android, so multi-threading is required)?

**Comment by leloupnicolas** [comment]
@mickaelpois,

I'm still investigating, and figured out, adding a breakpoint on `com.mangopay.core.RestTool.java:408`, that the URL called is "https://api.sandbox.mangopay.com/v2.01/{client_id}/wallets/{wallet_id}" with the GET method, and this HTTP call gets a 405 status code.

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Java SDK and Android use issue](https://trello.com/c/zcHLIABb/168-java-sdk-and-android-use-issue)

**Comment by catacraciun** [comment]
Hello @leloupnicolas ,

May I ask you why are you using the Java SDK directly into the android app? I suppose you are aware of the huge security risk you are facing by doing this.
I strongly recommend doing all communication with Mangopay through your private backend, and expose an API that can be used by your app.
