### ISSUE TITLE
Error Invalid client

### ISSUE THREAD

**Issue by niko227** [Mangopay/mangopay2-java-sdk#64]
Hi,
I'm receiving below exception when I'm trying to create a NaturaUser:
com.mangopay.core.ResponseException:  {"error":"invalid_client","error_description":"The authorization header was malformed or not recognized"}

create user call is done as the following:
...
try {
            new createUserNatural().execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
 
    private class createUserNatural extends AsyncTask<User,Void,User> {
        @Override
        protected User doInBackground(User... params) {
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                MangoPayApi api = new MangoPayApi();
                User user = new UserNatural();
                try {
                    user = api.Users.create(user);
                } catch (Exception e) {
                    e.printStackTrace();
                }              
                return user;
            }
            return null;
        }
 
        @Override
        protected void onPostExecute(User user) {
            System.out.println(user);
        }
    }
could you please help ?
thanks!

**Comment by mickaelpois** [comment]
Good morning @niko227 

Please have a look at our Readme page on GitHub, I guess it will be helpful.
It seems you don't have provided any clientId or password, which is absolutely mandatory to use our API:

```
import com.mangopay.MangoPayApi;

    // ...

    MangoPayApi api = new MangoPayApi();

    // configuration
    api.Config.ClientId = "your-client-id";
    api.Config.ClientPassword = "your-client-password";
    //api.Config.BaseUrl = "https://api.mangopay.com";

    // call some API methods...
    List<User> users = api.Users.getAll();
```

To ask for a sandbox account, nothing complicated: https://www.mangopay.com/en_UK/signup/create-sandbox/

For further informations, please contact our support team.

I hope it will be helpful!

Mickaël
