### ISSUE TITLE
Unable to create a PayIn after a PreAuthorization

### ISSUE THREAD

**Issue by gdpsy** [Mangopay/mangopay2-java-sdk#65]
Hello, 

I encounter an issue using the SDK. 

When trying to create a Card PreAuthorized PayIn, I've the following error : 

> [error] - application - java.lang.Exception: Execution is not defined or it is not object type
> [error] - application - Execution is not defined or it is not object type
> [warn] - application - Unable to parse response of MangoPay : com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Execution': was expecting ('true', 'false' or 'null')
>  at [Source: Execution is not defined or it is not object type; line: 1, column: 10]
> [error] - application - Error(Execution is not defined or it is not object type, None,  Some(java.lang.Thread.getStackTrace(Thread.java:1556)

It seems that it requires "setExecutionDetails" but it shouln't. 
Can you please give me a hand on it?
Thanks 

Here is the call : 
```
def create(idempotentToken: String, payIn: PayInPreAuth): Future[Expect[PayIn]] = {
    utils.Error.wrapMangoPay(mangoPayApi.payIns.create(idempotentToken, payIn))
  }
```

here is the PayIn build (from scala class)
```
implicit def toJava(pi: PayInPreAuth): com.mangopay.entities.PayIn = {
    val pij = new com.mangopay.entities.PayIn
    pij.setTag(pi.tag.orNull)
    pij.setAuthorId(pi.authorId)
    pij.setCreditedUserId(pi.creditedUserId.orNull)
    pij.setDebitedFunds(pi.debitedFunds)
    pij.setFees(pi.fees)
    pij.setPaymentType(PayInPaymentType.PREAUTHORIZED)
    pij.setPaymentDetails(pi.paymentDetails)
    pij.setExecutionType(PayInExecutionType.PREAUTHORIZED) // also tried with DIRECT  
    //pij.setExecutionDetails(pi.executionDetails)
    pij.setCreditedWalletId(pi.creditedWalletId)
    pij
  }
```

**Comment by mickaelpois** [comment]
Hello @gdpsy,

Sorry for this very late answer.
Is this issue always relevant?

Mickaël
