### ISSUE TITLE
RestTool castResponseToEntity() method doesn't handle enums correctly

### ISSUE THREAD

**Issue by didierWD** [Mangopay/mangopay2-java-sdk#7]
To reproduce:
Add to the hook creation test case (ApiHooksTest.test_Hooks_Get() ) an assert directive (sty like             assertEquals(getHook.EventType, hook.EventType);) to check that the hook's event type of the object returned by the creation is the same as the input event type (by the way it should already have been tested). See that null is always returned.

The cause is in the RestTool class, where it can be seen that the json to java conversion doesn't handle Enums at all.
Possible (really) dirty fix:
insert something like this i, the 'if (fieldIsArray)' code:
} else if (f.getType().isEnum()) {// Enumeration, try getting enum by name
	Class cls = f.getType();
	Object val = Enum.valueOf(cls, entry.getValue().getAsString());
	f.set(result, val);

and this in the else statement:
} else if (genericTypeClass.isEnum()) {// Enumeration, try getting enum by name
	Class cls = genericTypeClass;
	Object val = Enum.valueOf(cls, e.getAsJsonPrimitive().getAsString());
	addMethod.invoke(o, val);

**Comment by hobailey** [comment]
Hi @didierWD, sorry for the delay getting back to you,a nd thanks again for letting us know about the problem. Our investigation shows that there are some strings being used, where enums should in fact be used.
We're in the process of updating these and will release a new version of the SDK shortly with this resolved.

**Comment by hobailey** [comment]
Hi @didierWD, sorry for the delay with this, but we've just done https://github.com/Mangopay/mangopay2-java-sdk/commit/e462c71ca45c2e6e9e6068f20145a97baa1b9a58 to correct this bug.
