### ISSUE TITLE
Not implemented: List KYC Documents for a User

### ISSUE THREAD

**Issue by christianecker** [Mangopay/mangopay2-java-sdk#70]
Hi,

correct me if I'm wrong but is it possible you did not implement this method yet?
https://docs.mangopay.com/endpoints/v2.01/kyc-documents#e216_list-kyc-documents-for-a-user

Are there plans for updates?

Best regards

Christian

**Comment by mickaelpois** [comment]
Hello @christianecker 

Could `public List<KycDocument> getKycDocuments(String userId, Pagination pagination, Sorting sorting)` on `UserApiImpl.java` (Implementation of `ApiUsers.java` interface) be helpful?

Mickaël
