### ISSUE TITLE
BankWire Pay-In

### ISSUE THREAD

**Issue by mkbrv** [Mangopay/mangopay2-java-sdk#74]
Context: Sandbox
API: https://docs.mangopay.com/endpoints/v2.01/payins#e283_create-a-bankwire-payin-to-a-client-wallet

I am creating a bankwire pay-in with the following data: 

![image](https://user-images.githubusercontent.com/7677803/27914888-ce03601e-6264-11e7-9b13-a8a589292ac8.png)

In the dashboard I notice that the Pay In was created but the amount seems to not be taken:
![image](https://user-images.githubusercontent.com/7677803/27914804-8c168e56-6264-11e7-9154-0c7eb54bf65d.png)

Am I doing something wrong? 
Also why do I have to set a PayInExecutionDetails in the Java SDK ? ( it seems not to be required by the endpoint and I just set an object with all null properties)

**Comment by mkbrv** [comment]
I noticed the value is set in the Declared debited funds so perhaps the debited funds will not change because I am testing in a sandbox environment.

**Comment by hobailey** [comment]
Hey @mkbrv, you're right - the payin needs to be accepted on our side for these values to change, and since this is a manual task, in sandbox you'll need to contact our support team with the ID of the payment and they can do for you :-)
