### ISSUE TITLE
Add Asynchronous API

### ISSUE THREAD

**Issue by jannis-baratheon** [Mangopay/mangopay2-java-sdk#75]
It would be nice to have a possibility to call the Mangopay API asynchronously.

**Comment by mickaelpois** [comment]
Hello @jannis-baratheon,

Thanks for your proposal !
As an example, have you got any idea of why an asynchronous call could be helpful for your workflow?
Make this SDK asynchronous is not a high priority task for us (we are more focused on new features actually), but every good reason can make it coming faster !

**Comment by jannis-baratheon** [comment]
I'm not using your product anymore, but many serious server frameworks evolve towards reactive programming (Java itself as well). the asynchronous approach results in scalable and efficient server applications and IMHO much cleaner code. with spring 5 and spring reactive gaining traction you'll have to provide an asynchronous API or you'll stay behind. that's my opinion and with honesty I suggest raising priority on this one. most serious APIs provide asynchronous clients (eg Jira) and every serious HTTP client does as well (Apache, Jersey). just spend a moment reading about asynchronous HTTP communication in the server world and you'll get the picture. regards and good luck.
