### ISSUE TITLE
API transport security

### ISSUE THREAD

**Issue by PatrickPerc** [MangoPay/mangopay2-java-sdk#8]
Hello,
could you please elaborate about the security aspects when using API, mainly about transport part (what is embedded in SDK ?) and token management (is it requested on client part ?).
thanks

**Comment by hobailey** [comment]
Hi @PatrickPercevaux, all requests are done over SSL. And in terms of authentification, you can either use "Basic" authentification (where you transfer your ClientId and Passphrase with every call), or OAuth (where you use your ClientId and Passphrase to get a token that lasts for an hour, and you transfer this token with every call). The SDK uses the latter of these techniques.

**Comment by PatrickPercevaux** [comment]
Hi, Thanks for your prompt reply.
In case of OAuth: after requesting a token, is it the passphrase which should be replaced by the token value ? or OAuthTokenManager.storeToken(token) is for this usage, then client_id/passphrase couple shoud be left emply.
could you please advise ? 
Sorry, possibly that's newbie questions, but browsing MangoPay sites, I did not find javadocs of API or guidelines for such implementation.
KR

**Comment by hobailey** [comment]
Hi, sorry for the slow reply - have you managed to sort this now?

**Comment by PatrickPerc** [comment]
Hi, 
no progress on this, I was focusing on other topics and still working only with basic Oauth, I will implement token usage later on with your hints.
