### ISSUE TITLE
getUserApi - getNatural/getLegal user mapping error 

### ISSUE THREAD

**Issue by aliniftemi** [Mangopay/mangopay2-java-sdk#83]
Get user by id method in SDK does not map the KYCLevel field. Even if the server return the correct value (as JSON), inside the SDK, there is a method called castResponseToEntity(RestTool.java) which is supposed to fill the java object from a json object. This process is by comparing object members one by one. The issue is that , a camel case transformation, is supposed to compare value of a JSON field called FirstName with the name of a java object caled firstName and assign associated value. This comparison does not work properly for KYCLevel field compared with kycLevel field, which end up with a java object of type User having always the null value for kycLevel, no matter what the server returns.

**Comment by mickaelpois** [comment]
Hello @aliniftemi,

Thanks for your precious feedback.
We will analyse this issue very soon and try to provide a fix ASAP.
I will keep you posted here with any update.

Mickaël

**Comment by hobailey** [comment]
This has now been resolved with https://github.com/Mangopay/mangopay2-java-sdk/pull/85 :-)

**Comment by aliniftemi** [comment]
Hi,

Can you please make the change available in maven repository as well ?
Thanks

**Comment by aliniftemi** [comment]
Hi @mickaelpois ,

is there a chance to update maven repository as well soon ? We are based on sbt auto update in our infrastructure, and it is very difficult to put dependencies manually

Thanks

**Comment by mickaelpois** [comment]
Hi @aliniftemi, 
As you have may seen, a lot of PR have been merged yesterday evening on master branch.
Good news, a new major release will be available today !
