### ISSUE TITLE
Users.getNatural returns empty_body exception

### ISSUE THREAD

**Issue by PatrickPerc** [MangoPay/mangopay2-java-sdk#9]
Hi,
I'm receiving below exception when using Users.getNatural:
com.mangopay.core.ResponseException: Bad request. {"Message":"the body cannot be empty","Type":"empty_body","Id":"492c0812-18ac-46b2-b66f-d91acf6e8cfa","Date":1427290802.0,"errors":null}

getNatural API call is done as the following: 
try {
       UserNatural user=MangoApi.Users.getNatural(retUser.Id);
} catch (Exception e){....

Insert is done successfully just before by retUser=MangoApi.Users.create(newUser); 
then retUser.Id is correctly set ("6185965" value in my case).

could you please help ?
thx

**Comment by hobailey** [comment]
Hi @PatrickPerc, are you definitly using our SDK? Because I can't see how you could get this error with it :-/ 
This error is because you're doing a POST on the UserId and not a GET (hence we're expecting to have some body in that case).

**Comment by PatrickPerc** [comment]
sure, I've downloaded mangopaysdk.jar from this repository, linked it to my project "compile files('libs/mangopaysdk.jar')"
and in code
import com.mangopay.MangoPayApi;
import com.mangopay.entities.UserNatural;
MangoPayApi MangoApi = new MangoPayApi();
and so on so forth...
I can't see how I could not use the SDK.

I'm running all this stuff from android 422.

**Comment by hobailey** [comment]
Ah ok - our API is not currently compatitble with Android I'm afraid - we accept only server to server communications, so you'd have to set up your own internal API back to your own server, and then ping our API from there if that makes sense.

**Comment by PatrickPerc** [comment]
ok, that's a bad news...
is the android compatibility on your API roadmap ? or client / server comm is out of your strategy ?

**Comment by hobailey** [comment]
I've just checked this, and its actually not so much a question of compatability - its more a problem of security since you'd have to put a copy of your secret Passphrase into the app and then distribute this to everyone who uses your app...
I appreciate in your case it is also a question of compatibility which I'm not sure why with just what you've given here - if you send the whole bit of code to support@mangopay.com we can take a look for you.

**Comment by PatrickPerc** [comment]
ok, addressing a mail to support.
many thanks
